# Swamp and Mangrove Swamp variant for the small flower grass-block decoration
method=fixed
matchTiles=minecraft:block/grass_block/grass_block_top_flower_small
tiles=minecraft:block/grass_block/grass_block_top_flower_small_swamp
biomes=swamp mangrove_swamp
