# Swamp and Mangrove Swamp variant for the large flower grass-block decoration
method=fixed
matchTiles=minecraft:block/grass_block/grass_block_top_flower_big
tiles=minecraft:block/grass_block/grass_block_top_flower_big_swamp
biomes=swamp mangrove_swamp
